version: "3.7"

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "1338:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: server
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
